apiVersion: v1
kind: ConfigMap
metadata:
  name: dms-config
  namespace: dms
data:
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
  DATABASE_NAME: dms
  DATABASE_USER: dms
  REDIS_URL: redis://redis:6379/0
  CELERY_BROKER_URL: redis://redis:6379/0
  CELERY_RESULT_BACKEND: redis://redis:6379/1
  SWIFT_USER_UPLOADS_CONTAINER: proj26-user-uploads
  SWIFT_TRAINING_CONTAINER: proj26-training-data
