apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dms
resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - api.yaml
  - worker.yaml
  - scheduler.yaml
images:
  - name: ghcr.io/your-org/dms-app
    newName: ghcr.io/your-org/dms-app
    newTag: latest
