apiVersion: v1
kind: Service
metadata:
  name: metabase
  namespace: dms
spec:
  selector:
    app: metabase
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30081
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  namespace: dms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
        - name: metabase
          image: metabase/metabase:v0.56.3
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          env:
            - name: MB_DB_FILE
              value: /metabase-data/metabase.db
            - name: MB_SITE_NAME
              value: DMS Metabase
          volumeMounts:
            - name: metabase-data
              mountPath: /metabase-data
      volumes:
        - name: metabase-data
          persistentVolumeClaim:
            claimName: metabase-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metabase-data
  namespace: dms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
