apiVersion: v1
kind: Secret
metadata:
  name: dms-secrets
  namespace: dms
type: Opaque
stringData:
  DATABASE_PASSWORD: change-me
  SWIFT_AUTH_URL: https://chi.uc.chameleoncloud.org:5000/v3
  SWIFT_APP_CREDENTIAL_ID: replace-with-app-credential-id
  SWIFT_APP_CREDENTIAL_SECRET: replace-with-app-credential-secret
  KAGGLE_USERNAME: replace-with-kaggle-username
  KAGGLE_KEY: replace-with-kaggle-key
